spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT:1433};databaseName=${DB_NAME};encrypt=${DB_ENCRYPT:true};trustServerCertificate=${DB_TRUST_CERT:true}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

logging.level.root=warn
logging.level.org.hibernate.SQL=warn
